### ISSUE TITLE
Megaloot

### ISSUE THREAD

**Issue by TheThommynator** [TheLimePixel/Modern-Skyblock-3#247]
i got a helmet with luck 615 in my world som whenerver i kill a mob i get tonnes of reliquary drops
is it supposed to be like this?

**Comment by GreatBanoose** [comment]
The modpack author has confirmed that this is not a bug.  
https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/194

Only really seems to affect Reliquary drops though.   I have a helmet with 988 luck and usually get around 1 3/4 stacks of said reliquary drop each kill.

**Comment by TFCYoshi** [comment]
I get a helmet +3 Health, I equipped it and nothing happened, then when I remove it I lose 3 health lol!!

**Comment by SigmaChi07** [comment]
I think the larger problem that is overlooked by the majority of people on this issue is, yes, we know this isn't a bug, but the way this modpack's progression is supposed to work, it is supposed to be somewhat grindy. Kill a witch and getting 64 hats (21x6 redstone) or 1.5 stacks of nebulous/catalyzing/rib bone/zombie hearts/molten core, etc etc etc REALLY, REALLY ruins the progression flow. I'd understand if mobs dropped like potentially 10 of these items every now and then as a bonus, but 1.5 stacks of them literally every kill??? Come on... even Obama voters aren't that dumb.
