### ISSUE TITLE
Server restart on joining game

### ISSUE THREAD

**Issue by DragonBale** [TheLimePixel/Modern-Skyblock-3#266]
I have a G-Portal Server with the latest version of modern skyblock 3. I already playing this pack for a long time now and upated it very often. My last stand was that I finally got the iridium chicken and made some more mekanism machines. When suddenly the server restarted itself with no error and without a reason. Now it is always doing this when I just join the game. I downloaded the world and tried it on singleplayer and it is working fine. The only thing that also stopped working for a long time now is that I can't enter the nether and with that also can't enter the twilight forest but entering the aether works just fine. Most of the time I find the error out for myself and try to fix it but this time it's really just too weird and no errors are given. Maybe any ideas? Maybe it is self repairing after the next update? :'D

**Comment by Watschman** [comment]
Happens to us right now as well, suddenly the server restarts when a specific player joins it. There are no hints in any logfiles and no crash-report is generated. Interestingly it is also on a G-Portal Server. We will do some further investigation and if the problem persists going to move it to my dedicated server to see if the problem occurs there as well.
_________________________
edit:
After further investigation it turned out to be a much huger problem than initially thought. Since nobody looked in there questbook for a while we haven't noticed it immediately but apparently all Questprogress got reset (we were at like restart number 40).
The Owner decided to call me to administer the problem since I am working as an IT-Specialist and I have found no indication of an error in any log file whatsoever, so we decided to put in a backup before the first time the crash appeared. While doing this I noticed that the permission of the world folder was set to root:root and not to the normal user which G-Portal customers should receive, so possibly a mistake by the hosting company which caused the permission to change.
But anyways, after reverting to the backup things seem to be okay again. If anything else happens I will give an update.
____________________________
edit2:
Issue still persists after loading a backup file. Problem might be related to Mekanism since it started when our player who is furthest into the questbook hit the Mekanism questline.
___________________________
edit3:
Moved the world now to the dedicated server which is a lot more powerful than a gamehost, obviously. Now the issue is not happening again. Who knows what it actually is, definitely mysterious.

**Comment by sINFsehill** [comment]
Thanks alot for your effort to investigate it further! I have setup alot of minecraft servers now and mostly found the problem and fixed it. But this time around it's just to mysterious. Don't want to try to start fresh and see if this happens again because I already spend alot of time on getting so far :'D

**Comment by DragonBale** [comment]
Thanks alot for your effort to investigate it further! I have setup alot of minecraft servers now and mostly found the problem and fixed it. But this time around it's just to mysterious. Don't want to try to start fresh and see if this happens again because I already spend alot of time on getting so far :'D
