### ISSUE TITLE
Steel Gear recipe isn't working, but it's listed in JEI

### ISSUE THREAD

**Issue by shadow306k** [TheLimePixel/Modern-Skyblock-3#269]
After progressing far enough into Immersive Engineering to get steel, I wanted to use that to upgrade my casings to said metal, but the steel gear crafting recipe doesn't work. It shows there's one in JEI, but inserting the items using the [+] yields no result.
![2018-03-13_22 25 33](https://user-images.githubusercontent.com/20017282/37373247-bbf60912-270d-11e8-9f16-5325cf810b27.png)
![2018-03-13_22 25 39](https://user-images.githubusercontent.com/20017282/37373248-bc13b714-270d-11e8-956e-d61d4025decf.png)

**Comment by mcdodge34** [comment]
Until its fixed you can use a tinkers construct gear mold on the tinkers melter casting table.

**Comment by shadow306k** [comment]
I have Immersive Engineering access at this point anyway, so just made the multiblock machine for it.

**Comment by mcdodge34** [comment]
Yup, true, always forget these basic machines, and it turns out they could be useful, I end up using a crap ton of hammers and wire cutters, I'm up to a diesel generator and didn't build the metal press, will probably do it soon, once I get into tech reborn this will be very useful for various parts that need to be done.

**Comment by ffgda** [comment]
@EmosewaPixel If you tag an issue like that with "not a bug" and close it, could you add a short comment on why this isn't a bug? I just had the exact same issue and searched the issue tracker just to find this issue without any ellaboration.

On one hand in my oppinion it's bad practice to just close issues without a comment, on the other hand some insight might be helpful for other players searching for this issue and would reduce the time you have to spend to deal with repeating questions/reports.

Also on topic - I reckon this is intended by you because you're worried people could progress too quickly through the resource generation part of things if they had access to the steel casing. This is a non-factor though because you can get an end-stone (edit: mixed-up casing and condenser) condenser  relatviely easily...

**Comment by TheLimePixel** [comment]
There are other ways of making it. I only fix recipe conflicts when there is no other way of making it.

**Comment by ffgda** [comment]
I want to start with pointing out that I think the general approach to this modpack is great and that I'm enjoying it very much so far.

But also:
I don't want to be condescending but that's not how you handle software projects... (or any project for that matter). It might be low priority but it's a bug nonetheless...

I get that doing this takes a lot of effort but - just as some advice from someone who works on software projects for a living - if you want to be taken serious by the community (referring to https://www.reddit.com/r/feedthebeast/comments/7v93dc/anybody_playing_modern_skyblock_3/ for example), you should handle stuff like that differently.

**Comment by mcdodge34** [comment]
There's a very easy solution to this one in particular, yes there's other ways to craft it, for sure, but its a bug that is caused by teslacorelib, in the config of it you can simply tell the mod to not register gear recipes, I had the same issue in FTB Revelation regarding crafting simple copper gears or tin gears and this solved the issue. Maybe an option to take a look and see if this would help a lot of other potential players.
