### ISSUE TITLE
Flinging? Sudden launching off platform.

### ISSUE THREAD

**Issue by Vollykin** [TheLimePixel/Modern-Skyblock-3#282]
Not sure what to call it at all. Luckily I was recording just for fun and captured the weirdness. 
To describe what is happening in most of the videos, my left click seems to start hitting not in the center of the screen, and then every time I use the "WASD" movement keys I move a lot more than I should. Immediately after I do one of the these "Extra-Steps" I get flung in a direction as if suddenly I gained an extreme amount of velocity. Bonus video to show how I got back to the island and the weirdness more in action. Log files for the day attached, and videos trimmed.

https://drive.google.com/file/d/1VO2ZxjvOmauL3VPPc73vxxYRRirH0bSd/view?usp=sharing

**Comment by winVIP** [comment]
A similar thing happened to me when the character started waving his arm around and when I pressed wasd buttons the screen went dark or started flipping around.

**Comment by kevingoos** [comment]
yea same problem, and I think this has also todo with this, the torches rendering totally weird and then crashing because of fps lag~

Edit: I had it after updating from 3.1.5.3 to 3.2.0.1
I added a this video showing the glitch with the torches and flining arround on the platform: https://www.dropbox.com/s/29kq5feca89vvpa/glitch.mp4?dl=0)

**Comment by BraynStorm** [comment]
This is most probably caused by BetterFPS and in particular Tylor's Algorithm. (Will test in a few minutes). You can reproduce it by turning around like a lunatic 360 degrees **CCW** (just with the mouse is enough, no need to run in circles :D ) a couple of times.

#### Edit:
I found this while waiting for MC to restart :D https://github.com/Guichaguri/BetterFps/issues/92

#### Edit 2:
Yup, definetly "Tylor's Algorithm".

### Fix
Options -> BetterFPS -> Change the algorithm to something else, Riven's "Half" Algorithm is a good option.
