### ISSUE TITLE
sunny quartz slab bug

### ISSUE THREAD

**Issue by sreekrishn** [TheLimePixel/Modern-Skyblock-3#308]
![2018-03-26_18 13 23](https://user-images.githubusercontent.com/36627174/37907003-7dcb20fa-3121-11e8-9395-637e36405b81.png)

sunny quartz generating out of thin air

thts my tree farm frm industrial forgoing

**Comment by Daoenti** [comment]
This is also happening to the new agricraft stuff.  When I break the crop sticks that have a crop in them it places a Sunny Quartz Slab on top of where the crop sticks used to be.  The slab is a real block and I can harvest it and obtain it.

**Comment by KreatorB** [comment]
yeah and you get blue orchids from it!

**Comment by koosemose** [comment]
Had the same issue with agricraft stuff.
Running 3.2 Beta, in a world upgraded from 3.1.5.3

With a crop on cropsticks (tested with netherwart on soulsand and potatoes, carrots and wheat on tilled soil), when you break the cropstick, a sunny quartz slab is placed in the upper position on the block space formerly occupied by the cropsticks. Nethwart, potatoes, and carrots all return a blue orchid seed instead of the appropriate seed, while wheat returns the proper seed. Additionally tilled soil is changed immediately back to regular dirt (though this may simply be a side effect of the slab being placed, rather than a direct result). All problems occur the same rather the seed is analyzed or not.

I'm not sure if the Agricraft issue is the same as the one with the tree farm, but as one symptom and is the same and others have already reported the agricraft issue here, I've added this more detailed report here.

If any further information is needed, or a world save or anything, please let me know specifically, as what I have provided is all the potentially relevant information I can think of.

Addendum: As initial testing used actual carrots and potatoes, I went back and tested with the matching seeds and they do the exact same thing (replace top block with sunny quartz slab and drop blue orchid seed rather than the appropriate seed. 

I just noticed in followup testing, and additional sunny quartz slab is dropped when the crops are broken, and the sunny quartz slab portion happens even when breaking a crop stick with no crops on it.

**Comment by Bigbosseken** [comment]
Im using the industrial foregoing Gatherer- as its gathering crops its placing down sunny quartz. The crops are nothing more then normal minecraft crops (no agricraft sticks or any other mod).

**Comment by tollanes** [comment]
Can report that we have the same issue in 3.2 beta. What can we do to help isolate this issue?

**Comment by TheLimePixel** [comment]
This is just an issue with worlds that existed before 3.2. I don't know why it happens, nor how to fix it. As I often create new test world, I can't even reproduce it. Sorry everyone.

**Comment by tollanes** [comment]
Our server world was made yesterday with the current 3.2 pack.

**Comment by TheLimePixel** [comment]
...hmm....

**Comment by Trelander84** [comment]
Yup - made my world yesterday with fresh 3.2 install, every break of the cropsticks creates slabs. Any temp fixes by chance? Don't mind editing things myself if someone has a fix. Want to progress =)\

Edit: Updated to 3.2.1 and issue went away for cropsticks. Not sure about original OP issue with trees/differences but Agricraft crop sticks seems fine now.

Thanks =)

**Comment by MatthiasMann** [comment]
I have the same issue in single player with a freshly created world from the 3.2 server download files (as there is no curse launcher on Linux). This makes the whole agricraft farming really cumbersome.

**Comment by tollanes** [comment]
Just checked the new update and it has indeed fixed the agricraft bug on our server.

**Comment by MatthiasMann** [comment]
Could have been fixed by the KleeSlabs update: "Fixed air blocks being considered slabs, causing random slab generation while breaking air (e.g. via AOE hammers)"
