### ISSUE TITLE
Staged Quest

### ISSUE THREAD

**Issue by PeytonDavison** [TheLimePixel/Modern-Skyblock-3#37]
When playing in Staged mode sometimes when i leave i come back and a bunch of new quest lines appear. Happens when I leave game to switch videos then come back in.

**Comment by progheal** [comment]
The same happened in Gated mode too. Version: 3.0.2
What happened to me was, when I "Save and Quit to Title" then load back the world, a bunch of "Quest completed: New Quest" appears, the quest line is heavily messed up, and a lot of locked quest pages opened up.
![2018-02-04_17 51 19](https://user-images.githubusercontent.com/4156121/35776262-0c83efea-09d4-11e8-8de1-9be50ab122b3.png)
My progress until save & quit is just at "Basic resources / Basic Tinkering", but have submitted 32 FIrewood at the "Basic Farming And Automation" gate quest. It is also gone now.
(NB. I don't mind a restart since I've just a few hours in, but please fix this problem.)

**Comment by PeytonDavison** [comment]
The Exact thing happened to me, guess i'm just going to play Kitchen sink mode.

**Comment by TheLimePixel** [comment]
Yeah, revert to a backup. This can happen.

**Comment by PeytonDavison** [comment]
Thank You.
