### ISSUE TITLE
Add Ender IO once it's out and stable

### ISSUE THREAD

**Issue by TheLimePixel** [TheLimePixel/Modern-Skyblock-3#4]

**Comment by Ncrpts** [comment]
as of right now It's out :D

**Comment by RustyXXL** [comment]
I know, I might break stuff, but I'm adding it manually right now...man how I missed EnderIO in 1.12 :D

**Comment by RustyXXL** [comment]
Just a quick update:
I had to change the following 2 configs to get it running:

plustic.cfg
B:"Enable EnderIO integration"=false

moartinkers.cfg
B:"Allow Soularium Material"=false

I didn't check anything else atm, other than looking a bit through jei, because it's pretty late here already, also I'm in kitchensink mode anyway, but from whatever I can take from that it seems to be working so far.

**Comment by ThaDaVos** [comment]
https://minecraft.curseforge.com/projects/ender-io/files/2547475
I think it's out or it's an april fools joke

**Comment by ThaDaVos** [comment]
Check the top of the curseforge page: https://minecraft.curseforge.com/projects/ender-io

The following mods are known to crash when Ender IO is installed. This is not Ender IO's fault.
- Exchangers
- Foundry
- Moar Tinkers
- Plustic
- IC2
- DietHoppers (Old Versions)
- NuclearCraft

**Comment by RustyXXL** [comment]
Exchangers and Diet Hoppers are fixed in their latest versions, moar tinkers and plustic Are conflicting because EnderIO adds its own tinkers compatibility, deactivating the Materials like I posted before fixes the crashes without loosing functionality.

**Comment by oliverjanik** [comment]
@EmosewaPixel how will this fit gated mode?
