### ISSUE TITLE
End Dragon Not Spawned In

### ISSUE THREAD

**Issue by passh2o** [TheLimePixel/Modern-Skyblock-3#438]
I followed the change log suggestions of deleting the end dimension with one of the last updates but I still cant get the end dragon to spawn in when I teleport to the End. Tried the summon command with no luck as well. I've updated to the most recent version (3.3.1.2) in an effort to fix it but that hasn't solved it. I've tried deleting the dimension multiple times which is causing the end to rebuild itself but no dragon.

**Comment by TheL0ki** [comment]
Same issue here. Deleted the dimesnion and restarted server & client. When you teleport in, the health bar of the dragon appears but as soon as loading finished it disappears.

Also when you port back (either with the FTB Utils command, or RFTools or something else) everything in the overworld gets glitchy. AE2 can't autocraft anymore, Mobs shiver all the time, loot or xporb doesn't get collected anymore, it is not possible to go trough the nether portal. These are a few things i figured out so far.

**Comment by drewkeating** [comment]
I had the same issue of the end dragon not spawning. It's health bar would show for a second, but no dragon. I spawned it in with /summon ender_dragon ~ ~ ~ {DragonPhase:0} and just moved along with the pack. I had to use Journeymap to teleport home after the fight, though, because it didn't create the portal after the fight.

**Comment by TheLimePixel** [comment]
On world that were created before the latest version, the dragon simply will not spawn. However, the portal not spawning it...
