### ISSUE TITLE
Game Crash on startup

### ISSUE THREAD

**Issue by Tatzumori** [TheLimePixel/Modern-Skyblock-3#494]
Keep crashing on startup, i tried update video drivers, java and still crash.
Here's the log https://paste.ubuntu.com/p/9fMtBZKq7V/

**Comment by Soulyslayer** [comment]
Its happening my game too

**Comment by Caspygh** [comment]
Try reinstalling the modpack. Choose repair minecraft first from the modpack options and, if it still crashes, delete it and install it again. It may work.
As a note, updating java doesn't do anything since twitch uses a different java installation, not the installed one. You can take a look at the java problem here: 
https://www.reddit.com/r/feedthebeast/comments/80nhie/twitch_launcher_forcing_old_java_versions_on_you/

**Comment by TheLimePixel** [comment]
Obviously this is an Ubuntu-only issue.

**Comment by Tatzumori** [comment]
@EmosewaPixel No, i'm not using Ubuntu, i just used the Ubuntu's Pastebin because it don't have a maximum characters restriction like the normal Pastebin free.

**Comment by TheLimePixel** [comment]
Oh...

**Comment by TheLimePixel** [comment]
Have you tried launching the latest version?

**Comment by Tatzumori** [comment]
Ok guys, i think i've just found out the solution. I was running MSI Afterburner and Riva Tuner, 2 programs used to monitoring the temperatures, FPS, etc, and i tried to close them; magic happenz and DA-DAA! The game launched and i'm now able to play without any problem! I also tried opening MSI and Riva Tuner AFTER i launched the game and it work. So, if you have this kind of problems, try looking in the background for any applications, close them and start the game, it maybe work for you. I thanks all for the help you gave me and i hope someone will fix this kind of bugs.

**Comment by TheLimePixel** [comment]
Why did you reopen it?

**Comment by Tatzumori** [comment]
Just missclick, i'll close it now!
