### ISSUE TITLE
calculator mod,

### ISSUE THREAD

**Issue by frmrtxn** [TheLimePixel/Modern-Skyblock-3#503]
reinforced shovel and reinforced axe are uncraftable.. kinda. So, to create the sickle, you must first make the 2 previous tools. you can't. the only version available is from silent's gems, and isn't dictionaried,  so the sickle is uncraftable..

**Comment by Caspygh** [comment]
@frmrtxn Iirc this is because those items share the same recipes and MC favours the silent's gems one. A workaround is to craft a forestry worktable, which lets you choose the item output for conflicting recipes. As far as I know, this was the intended mechanics in Modern Skyblock 2. It may be intended here as well.
