### ISSUE TITLE
Claim not clickable and questline not contunie in questbook 

### ISSUE THREAD

**Issue by aoinal** [TheLimePixel/Modern-Skyblock-3#522]
After update (3.4) I just fnished plate jetpack quest and 2 next stage but cant click claim; reloaded questbook and all required lines turned into red. But I fnished all that quest. 

https://ibb.co/gC7QBJ
https://ibb.co/ebFZ5d
https://ibb.co/nsP5BJ

The trophy room Claim button  is not clickable too, I forgot to screen and close game

**Comment by Mc-man165** [comment]
I cant view those images, its giving me a 403 forbidden error. You might want to try another image hosting site like https://imgur.com/

**Comment by aoinal** [comment]
sorry imgur blocked in my country, an other suggestion ?

**Comment by Mc-man165** [comment]
Yes those work!

**Comment by Kzorith** [comment]
I think this and 523 are pretty much the same issue as I have the same problem with getting Pnumaticraft unlocked after completing Immersive Engineering.  Since there are three different quest lines having the issue, I'm going on a limb to say that none of them will complete properly.

I just started a test world from scratch and completing the Staged Mode quest doesn't unlock Basic Resources or Basic Tinkering.  So this is going to be a significant issue for anyone starting the pack.

Edit: Looks like this is addressed in Issue 506 and it's fixed in the development version, but not yet released.
