### ISSUE TITLE
A basic factory: Propane furnace is completed but "A True Blacksmith" is still locked

### ISSUE THREAD

**Issue by Mc-man165** [TheLimePixel/Modern-Skyblock-3#523]
I jumped into edit mode and it seems the hidden quest that unlocks "A true Blacksmith" is not completed even tough the quest it wants to be completed is.
https://i.imgur.com/vAdFMqI.jpg

I updated the pack and completed the Propane Furnace quest but it didn't unlock the "A True Blacksmith chapter"

**Comment by Kzorith** [comment]
I think this and 522 are pretty much the same issue as I have the same problem with getting Pnumaticraft unlocked after completing Immersive Engineering.  Since there are three different quest lines having the issue, I'm going on a limb to say that none of them will complete properly.

I just started a test world from scratch and completing the Staged Mode quest doesn't unlock Basic Resources or Basic Tinkering.  So this is going to be a significant issue for anyone starting the pack.

Edit: Looks like this is addressed in Issue 506 and it's fixed in the development version, but not yet released.
