### ISSUE TITLE
singleplayer block "roleback" bug

### ISSUE THREAD

**Issue by zaltao** [TheLimePixel/Modern-Skyblock-3#612]
i just can't destroy any block because the block break but the game seem to assume that the block i break are still there like a role back without visual or the bugs in supper early version of mc if one remember

**Comment by f0kx** [comment]
Hey 
its a bug with the (Beta) Version of the last update
you can solve it by your own if you downgrade the modpack or if you downgrade 1 mod!
1. ORE EXCAVATION to 1.4.118

EDIT:
pls read open issues first because #610 was also talking about it

"Ore Excavation 1.4.119 is incompatible with versions of Game Stages lower than 2.0.91 due to Ore Excavation requiring the new API introduced in version 2.0.91 of Game Stages. Currently the mod versions in the pack result in a server crash when a block is destroyed. Can be fixed by reverting Ore Excavation to 1.4.118.

Currently Factory Tech 1.5a causes a server crash when the pack is loaded. This can be resolved by reverting Factory Tech to 1.3.8."
